services:
  - type: web
    name: portifolio-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 3000
      - key: RESEND_API_KEY
        sync: false
      - key: RECEIVER_EMAIL
        sync: false
